export const subreddits = [
  [
    {
      id: 1,
      url:'/r/Homebrewing',
      icon_img:'',
      display_name:' Homebrewing',
    },
    {
      id: 2,
      url:'/r/TheHopyard',
      icon_img:'',
      display_name:' TheHopyard',
    },
    {
      id: 3,
      url:'/r/cider',
      icon_img:'',
      display_name:' cider',
    },
    {
      id: 4,
      url:'/r/TheMaltHouse',
      icon_img:'',
      display_name:' TheMaltHouse',
    },
    {
      id: 5,
      url:'/r/mead',
      icon_img:'',
      display_name:' mead',
    },
    {
      id: 6,
      url:'/r/HBL',
      icon_img:'',
      display_name:' HBL (labels)',
    },
    {
      id: 7,
      url:'/r/beer',
      icon_img:'',
      display_name:' beer',
    },
    {
      id: 9,
      url:'/r/brewing',
      icon_img:'',
      display_name:' bewing',
    },
    {
      id: 10,
      url:'/r/HomeBrewPorn',
      icon_img:'',
      display_name:' HomeBrewPorn',
    },
    {
      id: 11,
      url:'/r/HomeBrewLabels',
      icon_img:'',
      display_name:' HomeBrewLabels',
    },
    {
      id: 12,
      url:'/r/homebrewrecipes',
      icon_img:'',
      display_name:' homebrewrecipes',
    },
    {
      id: 13,
      url:'/r/Homebrewinghelp',
      icon_img:'',
      display_name:' Homebewinghelp',
    },
    {
      id: 14,
      url:'/r/homebrewingUK',
      icon_img:'',
      display_name:' homebrewingUK',
    },
    {
      id: 15,
      url:'/r/TheBrewery',
      icon_img:'',
      display_name:' TheBrewery',
    },
    {
      id: 16,
      url:'/r/hops',
      icon_img:'',
      display_name:' hops',
    },
  ],
  [
    {
      id: 0,
      url:'/r/theSopranos',
      icon_img:'',
      display_name:' theSopranos',
    },
    {
      id: 1,
      url:'/r/TalkingSopranos',
      icon_img:'',
      display_name:' TalkingSopranos',
    },
    {
      id: 2,
      url:'/r/CirclejerkSopranos',
      icon_img:'',
      display_name:' CirclejerkSopranos',
    },
    {
      id: 3,
      url:'/r/SopranosDiscussion',
      icon_img:'',
      display_name:' SopranosDiscussion',
    },
    {
      id: 4,
      url:'/r/SopranosSitdown',
      icon_img:'',
      display_name:' The Sopranos Sitdown',
    },
    {
      id: 5,
      url:'/r/Sopranosduckposting',
      icon_img:'',
      display_name:' Sopranosduckposting',
    },
    {
      id: 6,
      url:'/r/SopranosImmemorial',
      icon_img:'',
      display_name:' SopranosImmemorial',
    },
    {
      id: 7,
      url:'/r/SopranosPosting',
      icon_img:'',
      display_name:' Sopranos Memes',
    },
    {
      id: 8,
      url:'/r/Sopranos_TLOMO',
      icon_img:'',
      display_name:' Sopranos_TLOMO',
    },
    {
      id: 9,
      url:'/r/Sopranos_HBO_memes',
      icon_img:'',
      display_name:' Sopranos_HBO_memes',
    },
  ]
];